# -*- coding: utf-8 -*-
"""FOURTH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dhg2KSr_SMTogpHHqnRbRN9cmW6koN_Z
"""

#READ THE PICKLE FILES FROM PREVIOUS STAGES
#IN THE FOURTH BLOCK WE FORM CLUSTERS OF THE NUMBER OF IMAGES CAPTURED
#IN THE FIFTH BLOCK WE TRY TO PREDICT THE RECOGNITION IMAGE WITH THE CLUSTERS FORMED USING km.predict
#KMEANS CLUSTERING METHOD IS USED
#IN DICT1.PICKLE THERE ARE 



import pickle
import numpy as np

pickle_in = open("dict2.pickle" , "rb")
example_dict = pickle.load(pickle_in)
example_dict.shape
pickle_in = open("dict0.pickle" , "rb")
people = pickle.load(pickle_in)
people

import pickle
pickle_in = open("dict2.pickle" , "rb")
example_dict2 = pickle.load(pickle_in)
#print(example_dict2.shape)

import pickle
pickle_in = open("dict5.pickle" , "rb")
x_cap = pickle.load(pickle_in)
#print(x_cap.shape)

pickle_in = open("dict4.pickle" , "rb")
example_dict1 = pickle.load(pickle_in)
example_dict1.shape

from sklearn.cluster import KMeans
km = KMeans(n_clusters = people,random_state = 0)
y_km = km.fit_predict(x_cap)
#print(y_km)
# cluster = KMeans(n_clusters = people , random_state = 0).fit(example_dict1)
# arr = cluster.labels_
# print(arr)
# arr.shape

# from sklearn.cluster import KMeans
# cluster = KMeans(n_clusters=example_dict1,random_state=0).fit()
a = km.predict(example_dict1)
# pickle_in2 = open("dict4.pickle" , "rb")
# x_cap2 = pickle.load(pickle_in2)



pickle_in = open("dict1.pickle" , "rb")
name = pickle.load(pickle_in)
name = np.asarray(name)
print(name[a])

